package weka.classifiers.hw1;

public class NotImplementedException extends RuntimeException {

	/**
	 * serial auto generated by eclipse
	 */
	private static final long serialVersionUID = -2291736546696398504L;
	@Override
	public String toString() {
		return "Method is not supported.";
	}

}
